name: Deploy

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  deploy:
    uses: easydeploytest/EasyDeploy/.github/workflows/app-dispatch.yml@main
    with:
      repo: ${{ github.repository }}
      event_name: ${{ github.event_name }}
      sha: ${{ github.sha }}
      version: ${{ github.ref_name }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
